diagnostic_keyphrases = {
	0: ['normal fundus'], 
	1: ['nonproliferative retinopathy',
	'non proliferative retinopathy','mild nonproliferative retinopathy',
	'proliferative retinopathy','diabetic retinopathy', 'moderate non proliferative retinopathy',
	'hypertensive retinopathy', 'severe proliferative diabetic retinopathy', 'myopia retinopathy',
	'suspicious diabetic retinopathy', 'suspected diabetic retinopathy', 'myopic retinopathy'],
	2: ['glaucoma', 'suspected glaucoma', 'severe nonproliferative retinopathy',
	'proliferative diabetic retinopathy', 'suspected moderate non proliferative retinopathy'],
	3: ['cataract'],
	4: ['age-related macular degeneration', 'wet age-related macular degeneration',
	'dry age-related macular degeneration'],
	5: ['hypertensive'],
	6: ['myopi', 'pathological myopia'],
	7: ['macular epiretinal membrane',
	'epiretinal membrane',
	'drusen',
	'myelinated nerve fibers',
	'vitreous degeneration',
	'refractive media opacity',
	'spotted membranous change',
	'tessellated fundus',
	'maculopathy',
	'chorioretinal atrophy',
	'branch retinal vein occlusion',
	'retinal pigmentation',
	'white vessel',
	'post retinal laser surgery',
	'epiretinal membrane over the macula',
	'retinitis pigmentosa',
	'central retinal vein occlusion',
	'optic disc edema',
	'post laser photocoagulation',
	'retinochoroidal coloboma',
	'atrophic change',
	'optic nerve atrophy',
	'old branch retinal vein occlusion',
	'depigmentation of the retinal pigment epithelium',
	'chorioretinal atrophy with pigmentation proliferation',
	'central retinal artery occlusion',
	'old chorioretinopathy',
	'pigment epithelium proliferation',
	'retina fold',
	'abnormal pigment ',
	'idiopathic choroidal neovascularization',
	'branch retinal artery occlusion',
	'vessel tortuosity',
	'pigmentation disorder',
	'rhegmatogenous retinal detachment',
	'macular hole',
	'morning glory syndrome',
	'atrophy',
	'laser spot',
	'arteriosclerosis',
	'asteroid hyalosis',
	'congenital choroidal coloboma',
	'macular coloboma',
	'optic discitis',
	'oval yellow-white atrophy',
	'wedge-shaped change',
	'wedge white line change',
	'retinal artery macroaneurysm',
	'retinal vascular sheathing',
	'suspected abnormal color of  optic disc',
	'suspected retinal vascular sheathing',
	'suspected retinitis pigmentosa',
	'silicone oil eye',
	'punctate inner choroidopathy',
	'myopic maculopathy',
	'optic disk epiretinal membrane',
	'lens dust',
	'retinal pigment epithelium atrophy',
	'old choroiditis',
	'fundus laser photocoagulation spots',
	'diffuse retinal atrophy',
	'old central retinal vein occlusion',
	'intraretinal hemorrhage',
	'peripapillary atrophy',
	'choroidal nevus',
	'macular pigmentation disorder',
	'diffuse chorioretinal atrophy']}


diagnostic_normale_or_not = {
	0: ['normal fundus'], 
	1: ['nonproliferative retinopathy',
	'non proliferative retinopathy',
	'mild nonproliferative retinopathy',
	'proliferative retinopathy',
	'diabetic retinopathy',
	'moderate non proliferative retinopathy',
	'hypertensive retinopathy',
	'severe proliferative diabetic retinopathy',
	'myopia retinopathy',
	'suspicious diabetic retinopathy',
	'suspected diabetic retinopathy',
	'myopic retinopathy',
	'glaucoma',
	'suspected glaucoma',
	'severe nonproliferative retinopathy',
	'proliferative diabetic retinopathy',
	'suspected moderate non proliferative retinopathy',
	'cataract',
	'age-related macular degeneration',
	'wet age-related macular degeneration',
	'dry age-related macular degeneration',
	'hypertensive',
	'myopi',
	'pathological myopia',
	'macular epiretinal membrane',
	'epiretinal membrane',
	'drusen',
	'myelinated nerve fibers',
	'vitreous degeneration',
	'refractive media opacity',
	'spotted membranous change',
	'tessellated fundus',
	'maculopathy',
	'chorioretinal atrophy',
	'branch retinal vein occlusion',
	'retinal pigmentation',
	'white vessel',
	'post retinal laser surgery',
	'epiretinal membrane over the macula',
	'retinitis pigmentosa',
	'central retinal vein occlusion',
	'optic disc edema',
	'post laser photocoagulation',
	'retinochoroidal coloboma',
	'atrophic change',
	'optic nerve atrophy',
	'old branch retinal vein occlusion',
	'depigmentation of the retinal pigment epithelium',
	'chorioretinal atrophy with pigmentation proliferation',
	'central retinal artery occlusion',
	'old chorioretinopathy',
	'pigment epithelium proliferation',
	'retina fold',
	'abnormal pigment ',
	'idiopathic choroidal neovascularization',
	'branch retinal artery occlusion',
	'vessel tortuosity',
	'pigmentation disorder',
	'rhegmatogenous retinal detachment',
	'macular hole',
	'morning glory syndrome',
	'atrophy',
	'laser spot',
	'arteriosclerosis',
	'asteroid hyalosis',
	'congenital choroidal coloboma',
	'macular coloboma',
	'optic discitis',
	'oval yellow-white atrophy',
	'wedge-shaped change',
	'wedge white line change',
	'retinal artery macroaneurysm',
	'retinal vascular sheathing',
	'suspected abnormal color of  optic disc',
	'suspected retinal vascular sheathing',
	'suspected retinitis pigmentosa',
	'silicone oil eye',
	'punctate inner choroidopathy',
	'myopic maculopathy',
	'optic disk epiretinal membrane',
	'lens dust',
	'retinal pigment epithelium atrophy',
	'old choroiditis',
	'fundus laser photocoagulation spots',
	'diffuse retinal atrophy',
	'old central retinal vein occlusion',
	'intraretinal hemorrhage',
	'peripapillary atrophy',
	'choroidal nevus',
	'macular pigmentation disorder',
	'diffuse chorioretinal atrophy']}